name: humanidades360
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^10.2.0
  flutter_inappwebview: ^6.0.0-beta.22
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  google_maps_flutter: ^2.2.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  geolocator: ^14.0.1
  provider: ^6.1.5
  speech_to_text: 7.1.0
  flutter_tts: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_html: ^3.0.0
  html: ^0.15.0
  image_picker: ^0.8.7
  dotted_border: ^2.0.0
  webview_flutter: ^4.2.2
  path_provider: ^2.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_pdfview: ^1.4.1
  mailer: ^6.4.1
  logger: ^2.6.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/mapa_screen.png
    - assets/data/nodes.json
    - assets/data/nodos_conectados.json
    - assets/content/formulario_cae.html
    - assets/images/x.png
    - assets/images/fahu.png
    - assets/images/splash_icon.gif

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
